/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package dokter;

import Login.*;
import static Login.Main.*;
import java.util.ArrayList;
import model.Spesialis_kandungan;
import model.Spesialis_umum;

/**
 *
 * @author USER
 */
public class ProfileDokter extends javax.swing.JFrame {

    public static String spesialisDokter = "";
    public static int indexDok;
    public static int idDokter;

    /**
     * Creates new form profile
     *
     * @param jenis
     * @param index
     */
    public ProfileDokter(String jenis, int index) {
        spesialisDokter = jenis;
        indexDok = index;

        initComponents();
        if (jenis.equals("Umum")) {
            NamaDokter.setText(Spesialis_umum.get(index).getNama_dokter());
            Spesialis.setText(Spesialis_umum.get(index).getSpesialis());
            Email.setText(Spesialis_umum.get(index).getEmail());
            NomorTelp.setText(Spesialis_umum.get(index).getnoTelp());
            idDokter = Spesialis_umum.get(index).getId();

        } else if (jenis.equals("Penyakit Dalam")) {
            NamaDokter.setText(Spesialis_penyakitDalam.get(index).getNama_dokter());
            Spesialis.setText(Spesialis_penyakitDalam.get(index).getSpesialis());
            Email.setText(Spesialis_penyakitDalam.get(index).getEmail());
            NomorTelp.setText(Spesialis_penyakitDalam.get(index).getNoTelp());
            idDokter = Spesialis_penyakitDalam.get(index).getId();

        } else if (jenis.equals("Kandungan")) {
            NamaDokter.setText(Spesialis_kandungan.get(index).getNama_dokter());
            Spesialis.setText(Spesialis_kandungan.get(index).getSpesialis());
            Email.setText(Spesialis_kandungan.get(index).getEmail());
            NomorTelp.setText(Spesialis_kandungan.get(index).getnoTelp());
            idDokter = Spesialis_kandungan.get(index).getId();
        }
        else if (jenis.equals("THT")) {
            NamaDokter.setText(Spesialis_tht.get(index).getNama_dokter());
            Spesialis.setText(Spesialis_tht.get(index).getSpesialis());
            Email.setText(Spesialis_tht.get(index).getEmail());
            NomorTelp.setText(Spesialis_tht.get(index).getnoTelp());
            idDokter = Spesialis_tht.get(index).getId();
        }
        else if (jenis.equals("Mata")) {
            NamaDokter.setText(Spesialis_mata.get(index).getNama_dokter());
            Spesialis.setText(Spesialis_mata.get(index).getSpesialis());
            Email.setText(Spesialis_mata.get(index).getEmail());
            NomorTelp.setText(Spesialis_mata.get(index).getnoTelp());
            idDokter = Spesialis_mata.get(index).getId();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        timingTargetAdapter1 = new org.jdesktop.animation.timing.TimingTargetAdapter();
        timingTargetAdapter2 = new org.jdesktop.animation.timing.TimingTargetAdapter();
        timingTargetAdapter3 = new org.jdesktop.animation.timing.TimingTargetAdapter();
        timingTargetAdapter4 = new org.jdesktop.animation.timing.TimingTargetAdapter();
        timePicker1 = new com.raven.swing.TimePicker();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Logout = new javax.swing.JButton();
        Pw = new javax.swing.JPanel();
        Pass = new javax.swing.JLabel();
        TambahJanjiTemu = new javax.swing.JLabel();
        janji = new javax.swing.JPanel();
        JanjiTemu = new javax.swing.JLabel();
        textJanjiTemu = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        NomorTelp = new javax.swing.JTextField();
        Password = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        NamaDokter = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        Spesialis = new javax.swing.JTextField();
        Email = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(59, 172, 182));

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("DASHBOARD");

        jLabel2.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("DOKTER");

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/doctor (1).png"))); // NOI18N

        jLabel4.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Profil");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        Logout.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        Logout.setText("Logout");
        Logout.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutActionPerformed(evt);
            }
        });

        Pw.setBackground(new java.awt.Color(130, 219, 216));
        Pw.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(204, 204, 204), null));
        Pw.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PwMouseClicked(evt);
            }
        });

        Pass.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        Pass.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Pass.setText("Password");
        Pass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PassMouseClicked(evt);
            }
        });

        TambahJanjiTemu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TambahJanjiTemu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/password .png"))); // NOI18N
        TambahJanjiTemu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TambahJanjiTemuMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout PwLayout = new javax.swing.GroupLayout(Pw);
        Pw.setLayout(PwLayout);
        PwLayout.setHorizontalGroup(
            PwLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PwLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(PwLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PwLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(Pass))
                    .addComponent(TambahJanjiTemu, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PwLayout.setVerticalGroup(
            PwLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PwLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(TambahJanjiTemu, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Pass, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        janji.setBackground(new java.awt.Color(130, 219, 216));
        janji.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                janjiMouseClicked(evt);
            }
        });

        JanjiTemu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JanjiTemu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/calendar (1).png"))); // NOI18N
        JanjiTemu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JanjiTemuMouseClicked(evt);
            }
        });

        textJanjiTemu.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        textJanjiTemu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textJanjiTemu.setText("Janji Temu");
        textJanjiTemu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                textJanjiTemuMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout janjiLayout = new javax.swing.GroupLayout(janji);
        janji.setLayout(janjiLayout);
        janjiLayout.setHorizontalGroup(
            janjiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(janjiLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(textJanjiTemu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(janjiLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(JanjiTemu, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        janjiLayout.setVerticalGroup(
            janjiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(janjiLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JanjiTemu, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(textJanjiTemu, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Pw, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(janji, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addContainerGap(40, Short.MAX_VALUE))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(Logout)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Pw, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(janji, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Logout)
                .addContainerGap())
        );

        jLabel10.setText("Email");

        NomorTelp.setEditable(false);

        Password.setText("No Telphone");

        jLabel7.setText("Nama Dokter");

        NamaDokter.setEditable(false);
        NamaDokter.setText("123");
        NamaDokter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NamaDokterActionPerformed(evt);
            }
        });

        jLabel8.setText("Spesialis");

        Spesialis.setEditable(false);
        Spesialis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SpesialisActionPerformed(evt);
            }
        });

        Email.setEditable(false);

        jLabel5.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("PROFILE DOKTER");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel8)
                            .addComponent(jLabel7)
                            .addComponent(Password))
                        .addGap(84, 84, 84)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(NamaDokter, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE)
                            .addComponent(Spesialis)
                            .addComponent(Email)
                            .addComponent(NomorTelp))))
                .addGap(156, 156, 156))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(NamaDokter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Spesialis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(Email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NomorTelp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Password))
                .addGap(204, 204, 204))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutActionPerformed
        this.setVisible(false);
        new Login().setVisible(true);
    }//GEN-LAST:event_LogoutActionPerformed

    private void PassMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PassMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        new password().setVisible(true);

    }//GEN-LAST:event_PassMouseClicked

    private void TambahJanjiTemuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TambahJanjiTemuMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        new password().setVisible(true);
    }//GEN-LAST:event_TambahJanjiTemuMouseClicked

    private void JanjiTemuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JanjiTemuMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        new janjitemu().setVisible(true);
    }//GEN-LAST:event_JanjiTemuMouseClicked

    private void textJanjiTemuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textJanjiTemuMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        new janjitemu().setVisible(true);
    }//GEN-LAST:event_textJanjiTemuMouseClicked

    private void NamaDokterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NamaDokterActionPerformed
    }//GEN-LAST:event_NamaDokterActionPerformed

    private void SpesialisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SpesialisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SpesialisActionPerformed

    private void PwMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PwMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        new password().setVisible(true);
    }//GEN-LAST:event_PwMouseClicked

    private void janjiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_janjiMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        new janjitemu().setVisible(true);
    }//GEN-LAST:event_janjiMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProfileDokter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProfileDokter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProfileDokter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProfileDokter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProfileDokter(spesialisDokter, indexDok).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Email;
    private javax.swing.JLabel JanjiTemu;
    private javax.swing.JButton Logout;
    private javax.swing.JTextField NamaDokter;
    private javax.swing.JTextField NomorTelp;
    private javax.swing.JLabel Pass;
    private javax.swing.JLabel Password;
    private javax.swing.JPanel Pw;
    private javax.swing.JTextField Spesialis;
    private javax.swing.JLabel TambahJanjiTemu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel janji;
    private javax.swing.JLabel textJanjiTemu;
    private com.raven.swing.TimePicker timePicker1;
    private org.jdesktop.animation.timing.TimingTargetAdapter timingTargetAdapter1;
    private org.jdesktop.animation.timing.TimingTargetAdapter timingTargetAdapter2;
    private org.jdesktop.animation.timing.TimingTargetAdapter timingTargetAdapter3;
    private org.jdesktop.animation.timing.TimingTargetAdapter timingTargetAdapter4;
    // End of variables declaration//GEN-END:variables
}
